INSERT INTO PUBLIC.GENRE (NAME)
SELECT 'Комедия' UNION ALL
SELECT 'Драма' UNION ALL
SELECT 'Мультфильм' UNION ALL
SELECT 'Триллер' UNION ALL
SELECT 'Документальный' UNION ALL
SELECT 'Боевик'
WHERE NOT EXISTS (SELECT * FROM PUBLIC.GENRE);

INSERT INTO PUBLIC.MPA (name)
SELECT 'G' UNION ALL
SELECT 'PG' UNION ALL
SELECT 'PG-13' UNION ALL
SELECT 'R' UNION ALL
SELECT 'NC-17'
WHERE NOT EXISTS (SELECT * FROM PUBLIC.MPA);


